version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${APIPORT}:${APIPORT}
    depends_on:
      - db


  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
 
volumes: 
 data: {}